---
- name: Install tomcat server in ec2 
  hosts: all
  vars:
    download_url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.tar.gz   
  become: true
    tasks:
      - name: upgrade the system package
        ansible.builtin.apt:
          name: "*"
          state: latest

      - name: upgrade the system package
        ansible.builtin.apt:
          name: apache2
          state: latest    

      - name: Download Open JDK
        apt:
          name: openjdk-8-jre-headless
          update_cache: yes
          state: present

      - name: validate if Java is availble 
        shell: 
           java -version    
      
      - name: Create a Directory /opt/tomcat8
        file:
          path: /opt/tomcat8
          state: directory

      - name: Download Tomcat using unarchive
        unarchive:
          src: "{{download_url}}"
          dest: /opt/tomcat8
          remote_src: yes 

      - name: Move files to the /opt/tomcat8 directory
        shell: "mv /opt/tomcat8/apache*/* /opt/tomcat8"
    

      - name: Creating a service fille
        copy: 
          content: |-
            [Unit]
            Description=Tomcat Service
            Requires=network.target
            After=network.target
            [Service]
            Type=forking
            User=tomcat
            Environment="CATALINA_PID=/opt/tomcat8/logs/tomcat.pid"
            Environment="CATALINA_BASE=/opt/tomcat8"
            Environment="CATALINA_HOME=/opt/tomcat8"
            Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
            ExecStart=/opt/tomcat8/bin/startup.sh
            ExecStop=/opt/tomcat8/bin/shutdown.sh
            Restart=on-abnormal
            [Install]
            WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service

      - name: Reload the SystemD to re-read configuration
        systemd:
           daemon-reload: yes  

      - name: Enable the tomcat service and start
        systemd:
           name: tomcat
           enabled: yes
           state: started
     