---
      - name: upgrade the system package
        ansible.builtin.apt:
          name: "*"
          state: latest

      - name: upgrade the system package
        ansible.builtin.apt:
          name: apache2
          state: latest    

      - name: Download Open JDK
        apt:
          name: openjdk-8-jre-headless
          update_cache: yes
          state: present

      - name: validate if Java is availble 
        shell: 
           java -version    
      
      - name: Create a Directory /opt/tomcat8
        file:
          path: /opt/tomcat8
          state: directory

      - name: Download Tomcat using unarchive
        unarchive:
          src: "{{download_url}}"
          dest: /opt/tomcat8
          remote_src: yes 

      - name: Move files to the /opt/tomcat8 directory
        shell: "mv /opt/tomcat8/apache*/* /opt/tomcat8"
    

      - name : start tomcat
        shell: nohup  /opt/tomcat8/bin/startup.sh started

      - name: Run Tomcat
        shell: ./startup.sh
        args:
          chdir: /opt/tomcat8/bin   
